version: '3'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - '9191:9090'
    volumes:
      - /home/kali/BMS/DataVisualization
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
